### PR TITLE
Make some calculation use arrays instead of everytime calculation

### PR DESCRIPTION
**Pull request by yerenkow**
This pull request includes previous one (about caching largeEstimatorCutoff), so feel free accept anything from either one, or reimplement my proposed changes :)

### CODE REVIEW

**Comment by yerenkow** [comment]
Any comments? :)

**Comment by yerenkow** [comment]
Hi there :)

**Comment by ghost** [comment]
@yerenkow so, so, so sorry for the delay on this. i'll have this reviewed and merged this week. thanks for contributing!

**Comment by ghost** [comment]
@yerenkow Thanks again! I'll probably look at the other PR and then cut a release tomorrow.

**Pull request merged**
